#!/usr/bin/env python
import sys
import os
try:
    import http.server as SimpleHTTPServer # Python 3
except ImportError:
    import SimpleHTTPServer
try:
    import socketserver  # Python 3
except ImportError:
    import SocketServer as socketserver
import rospkg

rospack = rospkg.RosPack()
html_root = os.path.join(rospack.get_path('swri_profiler'), 'html')
try:
  os.chdir(html_root)
  print("Changing directory to: ", html_root)
except:
  print("Error changing directory to: ", html_root)

if len(sys.argv) > 1:
    PORT = int(sys.argv[1])
else:
    PORT = 8000

Handler = SimpleHTTPServer.SimpleHTTPRequestHandler

httpd = socketserver.TCPServer(("", PORT), Handler)

print("serving at port", PORT)
httpd.serve_forever()
